config/routes.rb
Rails.application.routes.draw do
  root "microposts#index"
  resources :microposts
  resources :users
  # For details on the DSL available
  # within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  message    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_microposts_on_user_id  (user_id)
#

class Micropost < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  first_name     :string
#  last_name      :string
#  email          :string
#  street_address :string
#  city           :string
#  province       :string
#  postal_code    :string
#  country        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class User < ApplicationRecord
  has_many :microposts

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  message    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_microposts_on_user_id  (user_id)
#

class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    #@microposts.paginate
    @microposts = Micropost.paginate(page: params[:page])
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:message, :user_id)
    end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  first_name     :string
#  last_name      :string
#  email          :string
#  street_address :string
#  city           :string
#  province       :string
#  postal_code    :string
#  country        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :street_address, :city, :province, :postal_code, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  message    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_microposts_on_user_id  (user_id)
#

module MicropostsHelper
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  first_name     :string
#  last_name      :string
#  email          :string
#  street_address :string
#  city           :string
#  province       :string
#  postal_code    :string
#  country        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bleater</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div id="container" class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= bootstrap_form_for(@micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :message, id: :micropost_message %>
  </div>

  <div class="field">
    <%= form.collection_select :user_id, User.all, :id, :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>Editing Micropost</h1>

    <%= render 'form', micropost: @micropost %>

    <%= link_to 'Show', @micropost %> |
    <%= link_to 'Back', microposts_path %>
  </div>
</div>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Microposts</h1>
      </div>

      <table class="table table-hover">
        <thead>
        <tr>
          <th>Message</th>
          <th>User</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @microposts.each do |micropost| %>
          <tr>
            <td><%= micropost.message %></td>
            <td><%= link_to micropost.user.email, user_path(micropost.user) %></td>
            <td>
              <div class="btn-group-vertical">
                <%= link_to 'Show', micropost, class: 'btn btn-default btn-sm' %>
                <%= link_to 'Edit', edit_micropost_path(micropost), class: 'btn btn-success btn-sm' %>
                <%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <%= link_to 'New Micropost', new_micropost_path, class: 'btn btn-default' %>
      </div>
      <%= will_paginate @microposts %>
    </div>
  </div>
</div>

app/views/microposts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>New Micropost</h1>

    <%= render 'form', micropost: @micropost %>

    <%= link_to 'Back', microposts_path %>
  </div>
</div>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-success">
      <div class="panel-heading">
        Micropost
      </div>

      <div class="panel-body">
        <p>
          <strong>Message:</strong>
          <%= @micropost.message %>
        </p>

        <p>
          <strong>User:</strong>
          <%= link_to @micropost.user.email, user_path(@micropost.user) %>
        </p>
      </div>

      <div class="panel-footer">
        <%= link_to 'Edit', edit_micropost_path(@micropost), class: "btn btn-success" %>
        <%= link_to 'Back', microposts_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Bleater", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Microposts", microposts_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Logout</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.text_field :street_address, id: :user_street_address %>
  </div>

  <div class="field">
    <%= form.text_field :city, id: :user_city %>
  </div>

  <div class="field">
    <%= form.text_field :province, id: :user_province %>
  </div>

  <div class="field">
    <%= form.text_field :postal_code, id: :user_postal_code %>
  </div>

  <div class="field">
    <%= form.text_field :country, id: :user_country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Users</h1>
      </div>

      <table class="table table-hover">
        <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td>
              <div class="btn-group-vertical">
                <%= link_to 'Show', user, class: 'btn btn-default btn-sm' %>
                <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-success btn-sm' %>
                <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <%= link_to 'New User', new_user_path, class: 'btn btn-default' %>
      </div>
      <%= will_paginate @users %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-success">
      <div class="panel-heading">
        User
      </div>

      <div class="panel-body">
        <p>
          <strong>First name:</strong>
          <%= @user.first_name %>
        </p>

        <p>
          <strong>Last name:</strong>
          <%= @user.last_name %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @user.email %>
        </p>

        <p>
          <strong>Street address:</strong>
          <%= @user.street_address %>
        </p>

        <p>
          <strong>City:</strong>
          <%= @user.city %>
        </p>

        <p>
          <strong>Province:</strong>
          <%= @user.province %>
        </p>

        <p>
          <strong>Postal code:</strong>
          <%= @user.postal_code %>
        </p>

        <p>
          <strong>Country:</strong>
          <%= @user.country %>
        </p>
      </div>

      <div class="panel-footer">
        <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-success' %>
        <%= link_to 'Back', users_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3><%= @user.first_name %>'s Microposts</h3>
      </div>
      <table class="table table-hover">
        <tr>
          <th class="col-md-10">Message</th>
          <th class="col-md-2"></th>
        </tr>
        <% @user.microposts.each do |micropost| %>
        <tr>
          <td><%= micropost.message %></td>
          <td><%= link_to "Show", micropost_path(micropost), class: 'btn btn-default' %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>